url: https://K-TechResearch.github.io
baseurl: /homepage/

# Site settings
title: Kondo giken
email: k8techresearch@gmail.com
description: "3DCAD,CAEをメインに，製造業のDXをサポート。主にFusion360とOSS（オープンソースソフトウェア）を使い，大企業には出来ないスピード・新技術を活用できます"


# Team names, titles and social links
people:
- name: Kondo
  pic: 1
  position: 個人事業主
  social:
    - title: github
      url: http://github.com/K-TechResearch
#    - title: facebook
#      url: #
#    - title: stack-overflow
#      url: #

#- name: Larry Parker
#  pic: 2
#  position: Lead Marketer
#  social:
#    - title: twitter
#      url: #
#    - title: facebook
#      url: #
#    - title: linkedin
#      url: #
#
#- name: Diana Petersen
#  pic: 3
#  position: Lead Developer
#  social:
#    - title: twitter
#      url: #
#    - title: facebook
#      url: #
#    - title: google-plus
#      url: #s

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
#  - title: twitter
#    url: http://twitter.com/jekyllrb
#  - title: facebook
#    url: 
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/jekyll
#  - title: bitbucket 
#    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/K-TechResearch

# Postal address (add as many lines as necessary)
address:
  - line: Aichi-pref, Japan
  - line: 他非公開

# Build settings
markdown: kramdown
permalink: pretty
